# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       sunxi-boards

# >> macros
# << macros

Summary:    Sys_config files of sunxi board variations
Version:    1.0
Release:    1
Group:      System/Boot
License:    GPLv2
URL:        http://linux-sunxi.org
Source0:    %{name}-%{version}.tar.bz2
Source1:    sunxi-boards-spec-file-helper.sh
Source2:    README-PACKAGER.txt
Source100:  sunxi-boards.yaml
BuildRequires:  sunxi-tools
Requires(post): /bin/mv
Requires(postun): /bin/mv

%description
Sunxi sys_config boot file variations


%package a10_mid_1gb
Summary:    Sys_config boot files of board a10_mid_1gb
Group:      System/Boot
Provides:   sunxi-board

%description a10_mid_1gb
This package contain board specifiy script.bin files


%package ba10_tv_box
Summary:    Sys_config boot files of board ba10_tv_box
Group:      System/Boot
Provides:   sunxi-board

%description ba10_tv_box
This package contain board specifiy script.bin files


%package coby_mid7042
Summary:    Sys_config boot files of board coby_mid7042
Group:      System/Boot
Provides:   sunxi-board

%description coby_mid7042
This package contain board specifiy script.bin files


%package coby_mid8042
Summary:    Sys_config boot files of board coby_mid8042
Group:      System/Boot
Provides:   sunxi-board

%description coby_mid8042
This package contain board specifiy script.bin files


%package coby_mid9742
Summary:    Sys_config boot files of board coby_mid9742
Group:      System/Boot
Provides:   sunxi-board

%description coby_mid9742
This package contain board specifiy script.bin files


%package cubieboard
Summary:    Sys_config boot files of board cubieboard
Group:      System/Boot
Provides:   sunxi-board

%description cubieboard
This package contain board specifiy script.bin files


%package cubieboard_512
Summary:    Sys_config boot files of board cubieboard_512
Group:      System/Boot
Provides:   sunxi-board

%description cubieboard_512
This package contain board specifiy script.bin files


%package dns_m82
Summary:    Sys_config boot files of board dns_m82
Group:      System/Boot
Provides:   sunxi-board

%description dns_m82
This package contain board specifiy script.bin files


%package gooseberry_a721
Summary:    Sys_config boot files of board gooseberry_a721
Group:      System/Boot
Provides:   sunxi-board

%description gooseberry_a721
This package contain board specifiy script.bin files


%package h6
Summary:    Sys_config boot files of board h6
Group:      System/Boot
Provides:   sunxi-board

%description h6
This package contain board specifiy script.bin files


%package hackberry
Summary:    Sys_config boot files of board hackberry
Group:      System/Boot
Provides:   sunxi-board

%description hackberry
This package contain board specifiy script.bin files


%package hyundai_a7hd
Summary:    Sys_config boot files of board hyundai_a7hd
Group:      System/Boot
Provides:   sunxi-board

%description hyundai_a7hd
This package contain board specifiy script.bin files


%package inet97f-ii
Summary:    Sys_config boot files of board inet97f-ii
Group:      System/Boot
Provides:   sunxi-board

%description inet97f-ii
This package contain board specifiy script.bin files


%package mele_a1000
Summary:    Sys_config boot files of board mele_a1000
Group:      System/Boot
Provides:   sunxi-board

%description mele_a1000
This package contain board specifiy script.bin files


%package mele_a1000g
Summary:    Sys_config boot files of board mele_a1000g
Group:      System/Boot
Provides:   sunxi-board

%description mele_a1000g
This package contain board specifiy script.bin files


%package mini-x-1gb
Summary:    Sys_config boot files of board mini-x-1gb
Group:      System/Boot
Provides:   sunxi-board

%description mini-x-1gb
This package contain board specifiy script.bin files


%package mini-x
Summary:    Sys_config boot files of board mini-x
Group:      System/Boot
Provides:   sunxi-board

%description mini-x
This package contain board specifiy script.bin files


%package mk802-1gb
Summary:    Sys_config boot files of board mk802-1gb
Group:      System/Boot
Provides:   sunxi-board

%description mk802-1gb
This package contain board specifiy script.bin files


%package mk802
Summary:    Sys_config boot files of board mk802
Group:      System/Boot
Provides:   sunxi-board

%description mk802
This package contain board specifiy script.bin files


%package mk802ii
Summary:    Sys_config boot files of board mk802ii
Group:      System/Boot
Provides:   sunxi-board

%description mk802ii
This package contain board specifiy script.bin files


%package pov_protab2_ips9
Summary:    Sys_config boot files of board pov_protab2_ips9
Group:      System/Boot
Provides:   sunxi-board

%description pov_protab2_ips9
This package contain board specifiy script.bin files


%package pov_protab2_ips_3g
Summary:    Sys_config boot files of board pov_protab2_ips_3g
Group:      System/Boot
Provides:   sunxi-board

%description pov_protab2_ips_3g
This package contain board specifiy script.bin files


%package uhost_u1a
Summary:    Sys_config boot files of board uhost_u1a
Group:      System/Boot
Provides:   sunxi-board

%description uhost_u1a
This package contain board specifiy script.bin files


%package zatab
Summary:    Sys_config boot files of board zatab
Group:      System/Boot
Provides:   sunxi-board

%description zatab
This package contain board specifiy script.bin files


%package mk802plus_a10s
Summary:    Sys_config boot files of board mk802plus_a10s
Group:      System/Boot
Provides:   sunxi-board

%description mk802plus_a10s
This package contain board specifiy script.bin files


%package r7
Summary:    Sys_config boot files of board r7
Group:      System/Boot
Provides:   sunxi-board

%description r7
This package contain board specifiy script.bin files


%package a13_mid
Summary:    Sys_config boot files of board a13_mid
Group:      System/Boot
Provides:   sunxi-board

%description a13_mid
This package contain board specifiy script.bin files


%package a13_olinuxino
Summary:    Sys_config boot files of board a13_olinuxino
Group:      System/Boot
Provides:   sunxi-board

%description a13_olinuxino
This package contain board specifiy script.bin files


%package pcduino
Summary:    Sys_config boot files of board pcduino
Group:      System/Boot
Provides:   sunxi-board

%description pcduino
This package contain board specifiy script.bin files


%package eoma68-a10
Summary:    Sys_config boot files of board eoma68-a10
Group:      System/Boot
Provides:   sunxi-board

%description eoma68-a10
This package contain board specifiy script.bin files

%package A31_EVB
Summary:    Sys_config boot files of board A31_EVB
Group:      System/Boot
Provides:   sunxi-board

%description  A31_EVB
This package contain board specifiy script.bin files

%package a10s-olinuxino-m-lcd10
Summary:    Sys_config boot files of board a10s-olinuxino-m-lcd10
Group:      System/Boot
Provides:   sunxi-board

%description  a10s-olinuxino-m-lcd10
This package contain board specifiy script.bin files

%package a10s-olinuxino-m-lcd7
Summary:    Sys_config boot files of board a10s-olinuxino-m-lcd7
Group:      System/Boot
Provides:   sunxi-board

%description  a10s-olinuxino-m-lcd7
This package contain board specifiy script.bin files

%package a10s-olinuxino-m
Summary:    Sys_config boot files of board a10s-olinuxino-m
Group:      System/Boot
Provides:   sunxi-board

%description  a10s-olinuxino-m
This package contain board specifiy script.bin files

%package a13-olinuxino-lcd10
Summary:    Sys_config boot files of board a13-olinuxino-lcd10
Group:      System/Boot
Provides:   sunxi-board

%description  a13-olinuxino-lcd10
This package contain board specifiy script.bin files

%package a13-olinuxino-lcd7
Summary:    Sys_config boot files of board a13-olinuxino-lcd7
Group:      System/Boot
Provides:   sunxi-board

%description  a13-olinuxino-lcd7
This package contain board specifiy script.bin files

%package a13-olinuxinom-lcd10
Summary:    Sys_config boot files of board a13-olinuxinom-lcd10
Group:      System/Boot
Provides:   sunxi-board

%description  a13-olinuxinom-lcd10
This package contain board specifiy script.bin files

%package a13-olinuxinom-lcd7
Summary:    Sys_config boot files of board a13-olinuxinom-lcd7
Group:      System/Boot
Provides:   sunxi-board

%description  a13-olinuxinom-lcd7
This package contain board specifiy script.bin files

%package a13-olinuxinom
Summary:    Sys_config boot files of board a13-olinuxinom
Group:      System/Boot
Provides:   sunxi-board

%description  a13-olinuxinom
This package contain board specifiy script.bin files

%package a20-olinuxino_micro-lcd10
Summary:    Sys_config boot files of board a20-olinuxino_micro-lcd10
Group:      System/Boot
Provides:   sunxi-board

%description  a20-olinuxino_micro-lcd10
This package contain board specifiy script.bin files

%package a20-olinuxino_micro-lcd7
Summary:    Sys_config boot files of board a20-olinuxino_micro-lcd7
Group:      System/Boot
Provides:   sunxi-board

%description  a20-olinuxino_micro-lcd7
This package contain board specifiy script.bin files

%package a20-olinuxino_micro
Summary:    Sys_config boot files of board a20-olinuxino_micro
Group:      System/Boot
Provides:   sunxi-board

%description  a20-olinuxino_micro
This package contain board specifiy script.bin files

%package a70x
Summary:    Sys_config boot files of board a70x
Group:      System/Boot
Provides:   sunxi-board

%description  a70x
This package contain board specifiy script.bin files

%package auxtek-t003
Summary:    Sys_config boot files of board auxtek-t003
Group:      System/Boot
Provides:   sunxi-board

%description  auxtek-t003
This package contain board specifiy script.bin files

%package auxtek-t004
Summary:    Sys_config boot files of board auxtek-t004
Group:      System/Boot
Provides:   sunxi-board

%description  auxtek-t004
This package contain board specifiy script.bin files

%package cubieboard2
Summary:    Sys_config boot files of board cubieboard2
Group:      System/Boot
Provides:   sunxi-board

%description  cubieboard2
This package contain board specifiy script.bin files

%package cubietruck
Summary:    Sys_config boot files of board cubietruck
Group:      System/Boot
Provides:   sunxi-board

%description  cubietruck
This package contain board specifiy script.bin files

%package eu3000
Summary:    Sys_config boot files of board eu3000
Group:      System/Boot
Provides:   sunxi-board

%description  eu3000
This package contain board specifiy script.bin files

%package hd12-a20-v1
Summary:    Sys_config boot files of board hd12-a20-v1
Group:      System/Boot
Provides:   sunxi-board

%description  hd12-a20-v1
This package contain board specifiy script.bin files

%package iteaduino_plus_a10
Summary:    Sys_config boot files of board iteaduino_plus_a10
Group:      System/Boot
Provides:   sunxi-board

%description  iteaduino_plus_a10
This package contain board specifiy script.bin files

%package iteaduino_plus_a20
Summary:    Sys_config boot files of board iteaduino_plus_a20
Group:      System/Boot
Provides:   sunxi-board

%description  iteaduino_plus_a20
This package contain board specifiy script.bin files

%package k1001l1c
Summary:    Sys_config boot files of board k1001l1c
Group:      System/Boot
Provides:   sunxi-board

%description  k1001l1c
This package contain board specifiy script.bin files

%package ltm7
Summary:    Sys_config boot files of board ltm7
Group:      System/Boot
Provides:   sunxi-board

%description  ltm7
This package contain board specifiy script.bin files

%package marsboard_a10
Summary:    Sys_config boot files of board marsboard_a10
Group:      System/Boot
Provides:   sunxi-board

%description  marsboard_a10
This package contain board specifiy script.bin files

%package megafeis_a08
Summary:    Sys_config boot files of board megafeis_a08
Group:      System/Boot
Provides:   sunxi-board

%description  megafeis_a08
This package contain board specifiy script.bin files

%package mele-a1000g-quad
Summary:    Sys_config boot files of board mele-a1000g-quad
Group:      System/Boot
Provides:   sunxi-board

%description  mele-a1000g-quad
This package contain board specifiy script.bin files

%package mele_a3700
Summary:    Sys_config boot files of board mele_a3700
Group:      System/Boot
Provides:   sunxi-board

%description  mele_a3700
This package contain board specifiy script.bin files

%package mini-x_a10s
Summary:    Sys_config boot files of board mini-x_a10s
Group:      System/Boot
Provides:   sunxi-board

%description  mini-x_a10s
This package contain board specifiy script.bin files

%package myaudio-708m
Summary:    Sys_config boot files of board myaudio-708m
Group:      System/Boot
Provides:   sunxi-board

%description  myaudio-708m
This package contain board specifiy script.bin files

%package sanei_n90
Summary:    Sys_config boot files of board sanei_n90
Group:      System/Boot
Provides:   sunxi-board

%description  sanei_n90
This package contain board specifiy script.bin files

%package szenio_1207c4
Summary:    Sys_config boot files of board szenio_1207c4
Group:      System/Boot
Provides:   sunxi-board

%description  szenio_1207c4
This package contain board specifiy script.bin files

%package wobo-i5
Summary:    Sys_config boot files of board wobo-i5
Group:      System/Boot
Provides:   sunxi-board

%description  wobo-i5
This package contain board specifiy script.bin files

%package xzpad700
Summary:    Sys_config boot files of board xzpad700
Group:      System/Boot
Provides:   sunxi-board

%description  xzpad700
This package contain board specifiy script.bin files

%package yarvik_tab260
Summary:    Sys_config boot files of board yarvik_tab260
Group:      System/Boot
Provides:   sunxi-board

%description  yarvik_tab260
This package contain board specifiy script.bin files

%package jesurun-q5
Summary:    Sys_config boot files of board jesurun-q5
Group:      System/Boot
Provides:   sunxi-board

%description  jesurun-q5
This package contain board specifiy script.bin files

%prep
#%define _buildrootdir %{_topdir}/BUILDROOT

%setup -q -n %{name}-%{version}/sunxi-boards

# >> setup
# << setup

%build
# >> build pre
BOARD_CONFIGS=$(find -name "*.fex")
for board_config in ${BOARD_CONFIGS}; do
BOARD_SCRIPT_BIN=$(basename ${board_config} | sed 's|\.fex|-script.bin|g')
fex2bin ${board_config} ${BOARD_SCRIPT_BIN}
done
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
mkdir -p %{buildroot}/boot/
cp -a *script.bin %{buildroot}/boot/
# << install post


%post a10_mid_1gb
mv /boot/a10_mid_1gb-script.bin /boot/script.bin

%preun a10_mid_1gb
mv /boot/script.bin /boot/a10_mid_1gb-script.bin


%post ba10_tv_box
mv /boot/ba10_tv_box-script.bin /boot/script.bin

%preun ba10_tv_box
mv /boot/script.bin /boot/ba10_tv_box-script.bin

%post coby_mid7042
mv /boot/coby_mid7042-script.bin /boot/script.bin

%preun coby_mid7042
mv /boot/script.bin /boot/coby_mid7042-script.bin

%post coby_mid8042
mv /boot/coby_mid8042-script.bin /boot/script.bin

%preun coby_mid8042
mv /boot/script.bin /boot/coby_mid8042-script.bin

%post coby_mid9742
mv /boot/coby_mid9742-script.bin /boot/script.bin

%preun coby_mid9742
mv /boot/script.bin /boot/coby_mid9742-script.bin

%post cubieboard
mv /boot/cubieboard-script.bin /boot/script.bin

%preun cubieboard
mv /boot/script.bin /boot/cubieboard-script.bin

%post cubieboard_512
mv /boot/cubieboard_512-script.bin /boot/script.bin

%preun cubieboard_512
mv /boot/script.bin /boot/cubieboard_512-script.bin

%post dns_m82
mv /boot/dns_m82-script.bin /boot/script.bin

%preun dns_m82
mv /boot/script.bin /boot/dns_m82-script.bin

%post gooseberry_a721
mv /boot/gooseberry_a721-script.bin /boot/script.bin

%preun gooseberry_a721
mv /boot/script.bin /boot/gooseberry_a721-script.bin

%post h6
mv /boot/h6-script.bin /boot/script.bin

%preun h6
mv /boot/script.bin /boot/h6-script.bin

%post hackberry
mv /boot/hackberry-script.bin /boot/script.bin

%preun hackberry
mv /boot/script.bin /boot/hackberry-script.bin

%post hyundai_a7hd
mv /boot/hyundai_a7hd-script.bin /boot/script.bin

%preun hyundai_a7hd
mv /boot/script.bin /boot/hyundai_a7hd-script.bin

%post inet97f-ii
mv /boot/inet97f-ii-script.bin /boot/script.bin

%preun inet97f-ii
mv /boot/script.bin /boot/inet97f-ii-script.bin

%post mele_a1000
mv /boot/mele_a1000-script.bin /boot/script.bin

%preun mele_a1000
mv /boot/script.bin /boot/mele_a1000-script.bin

%post mele_a1000g
mv /boot/mele_a1000g-script.bin /boot/script.bin

%preun mele_a1000g
mv /boot/script.bin /boot/mele_a1000g-script.bin

%post mini-x-1gb
mv /boot/mini-x-1gb-script.bin /boot/script.bin

%preun mini-x-1gb
mv /boot/script.bin /boot/mini-x-1gb-script.bin

%post mini-x
mv /boot/mini-x-script.bin /boot/script.bin

%preun mini-x
mv /boot/script.bin /boot/mini-x-script.bin

%post mk802-1gb
mv /boot/mk802-1gb-script.bin /boot/script.bin

%preun mk802-1gb
mv /boot/script.bin /boot/mk802-1gb-script.bin

%post mk802
mv /boot/mk802-script.bin /boot/script.bin

%preun mk802
mv /boot/script.bin /boot/mk802-script.bin

%post mk802ii
mv /boot/mk802ii-script.bin /boot/script.bin

%preun mk802ii
mv /boot/script.bin /boot/mk802ii-script.bin

%post pov_protab2_ips9
mv /boot/pov_protab2_ips9-script.bin /boot/script.bin

%preun pov_protab2_ips9
mv /boot/script.bin /boot/pov_protab2_ips9-script.bin

%post pov_protab2_ips_3g
mv /boot/pov_protab2_ips_3g-script.bin /boot/script.bin

%preun pov_protab2_ips_3g
mv /boot/script.bin /boot/pov_protab2_ips_3g-script.bin

%post uhost_u1a
mv /boot/uhost_u1a-script.bin /boot/script.bin

%preun uhost_u1a
mv /boot/script.bin /boot/uhost_u1a-script.bin

%post zatab
mv /boot/zatab-script.bin /boot/script.bin

%preun zatab
mv /boot/script.bin /boot/zatab-script.bin

%post mk802plus_a10s
mv /boot/mk802plus_a10s-script.bin /boot/script.bin

%preun mk802plus_a10s
mv /boot/script.bin /boot/mk802plus_a10s-script.bin

%post r7
mv /boot/r7-script.bin /boot/script.bin

%preun r7
mv /boot/script.bin /boot/r7-script.bin

%post a13_mid
mv /boot/a13_mid-script.bin /boot/script.bin

%preun a13_mid
mv /boot/script.bin /boot/a13_mid-script.bin

%post a13_olinuxino
mv /boot/a13_olinuxino-script.bin /boot/script.bin

%preun a13_olinuxino
mv /boot/script.bin /boot/a13_olinuxino-script.bin

%post pcduino
mv /boot/pcduino-script.bin /boot/script.bin

%preun pcduino
mv /boot/script.bin /boot/pcduino-script.bin

%post eoma68-a10
mv /boot/eoma68_a10-script.bin /boot/script.bin

%preun eoma68-a10
mv /boot/script.bin /boot/eoma68_a10-script.bin

%post A31_EVB
mv /boot/A31_EVB-script.bin /boot/script.bin

%preun A31_EVB
mv /boot/script.bin /boot/A31_EVB-script.bin

%post a10s-olinuxino-m-lcd10
mv /boot/a10s-olinuxino-m-lcd10-script.bin /boot/script.bin

%preun a10s-olinuxino-m-lcd10
mv /boot/script.bin /boot/a10s-olinuxino-m-lcd10-script.bin

%post a10s-olinuxino-m-lcd7
mv /boot/a10s-olinuxino-m-lcd7-script.bin /boot/script.bin

%preun a10s-olinuxino-m-lcd7
mv /boot/script.bin /boot/a10s-olinuxino-m-lcd7-script.bin

%post a10s-olinuxino-m
mv /boot/a10s-olinuxino-m-script.bin /boot/script.bin

%preun a10s-olinuxino-m
mv /boot/script.bin /boot/a10s-olinuxino-m-script.bin

%post a13-olinuxino-lcd10
mv /boot/a13-olinuxino-lcd10-script.bin /boot/script.bin

%preun a13-olinuxino-lcd10
mv /boot/script.bin /boot/a13-olinuxino-lcd10-script.bin

%post a13-olinuxino-lcd7
mv /boot/a13-olinuxino-lcd7-script.bin /boot/script.bin

%preun a13-olinuxino-lcd7
mv /boot/script.bin /boot/a13-olinuxino-lcd7-script.bin

%post a13-olinuxinom-lcd10
mv /boot/a13-olinuxinom-lcd10-script.bin /boot/script.bin

%preun a13-olinuxinom-lcd10
mv /boot/script.bin /boot/a13-olinuxinom-lcd10-script.bin

%post a13-olinuxinom-lcd7
mv /boot/a13-olinuxinom-lcd7-script.bin /boot/script.bin

%preun a13-olinuxinom-lcd7
mv /boot/script.bin /boot/a13-olinuxinom-lcd7-script.bin

%post a13-olinuxinom
mv /boot/a13-olinuxinom-script.bin /boot/script.bin

%preun a13-olinuxinom
mv /boot/script.bin /boot/a13-olinuxinom-script.bin

%post a20-olinuxino_micro-lcd10
mv /boot/a20-olinuxino_micro-lcd10-script.bin /boot/script.bin

%preun a20-olinuxino_micro-lcd10
mv /boot/script.bin /boot/a20-olinuxino_micro-lcd10-script.bin

%post a20-olinuxino_micro-lcd7
mv /boot/a20-olinuxino_micro-lcd7-script.bin /boot/script.bin

%preun 
mv /boot/script.bin /boot/a20-olinuxino_micro-lcd7-script.bin

%post a20-olinuxino_micro
mv /boot/a20-olinuxino_micro-script.bin /boot/script.bin

%preun a20-olinuxino_micro
mv /boot/script.bin /boot/a20-olinuxino_micro-script.bin

%post a70x
mv /boot/a70x-script.bin /boot/script.bin

%preun a70x
mv /boot/script.bin /boot/a70x-script.bin

%post auxtek-t003
mv /boot/auxtek-t003-script.bin /boot/script.bin

%preun auxtek-t003
mv /boot/script.bin /boot/auxtek-t003-script.bin

%post auxtek-t004
mv /boot/auxtek-t004-script.bin /boot/script.bin

%preun auxtek-t004
mv /boot/script.bin /boot/auxtek-t004-script.bin

%post cubieboard2
mv /boot/cubieboard2-script.bin /boot/script.bin

%preun cubieboard2
mv /boot/script.bin /boot/cubieboard2-script.bin

%post cubietruck
mv /boot/cubietruck-script.bin /boot/script.bin

%preun cubietruck
mv /boot/script.bin /boot/cubietruck-script.bin

%post eu3000
mv /boot/eu3000-script.bin /boot/script.bin

%preun eu3000
mv /boot/script.bin /boot/eu3000-script.bin

%post hd12-a20-v1
mv /boot/hd12-a20-v1-script.bin /boot/script.bin

%preun hd12-a20-v1
mv /boot/script.bin /boot/hd12-a20-v1-script.bin

%post iteaduino_plus_a10
mv /boot/iteaduino_plus_a10-script.bin /boot/script.bin

%preun iteaduino_plus_a10
mv /boot/script.bin /boot/iteaduino_plus_a10-script.bin

%post iteaduino_plus_a20
mv /boot/iteaduino_plus_a20-script.bin /boot/script.bin

%preun iteaduino_plus_a20
mv /boot/script.bin /boot/iteaduino_plus_a20-script.bin

%post k1001l1c
mv /boot/k1001l1c-script.bin /boot/script.bin

%preun k1001l1c
mv /boot/script.bin /boot/k1001l1c-script.bin

%post ltm7
mv /boot/ltm7-script.bin /boot/script.bin

%preun ltm7
mv /boot/script.bin /boot/ltm7-script.bin

%post marsboard_a10
mv /boot/marsboard_a10-script.bin /boot/script.bin

%preun marsboard_a10
mv /boot/script.bin /boot/marsboard_a10-script.bin

%post megafeis_a08
mv /boot/megafeis_a08-script.bin /boot/script.bin

%preun megafeis_a08
mv /boot/script.bin /boot/megafeis_a08-script.bin

%post mele-a1000g-quad
mv /boot/mele-a1000g-quad-script.bin /boot/script.bin

%preun mele-a1000g-quad
mv /boot/script.bin /boot/mele-a1000g-quad-script.bin

%post mele_a3700
mv /boot/mele_a3700-script.bin /boot/script.bin

%preun mele_a3700
mv /boot/script.bin /boot/mele_a3700-script.bin

%post mini-x_a10s
mv /boot/mini-x_a10s-script.bin /boot/script.bin

%preun mini-x_a10s
mv /boot/script.bin /boot/mini-x_a10s-script.bin

%post myaudio-708m
mv /boot/myaudio-708m-script.bin /boot/script.bin

%preun myaudio-708m
mv /boot/script.bin /boot/myaudio-708m-script.bin

%post sanei_n90
mv /boot/sanei_n90-script.bin /boot/script.bin

%preun sanei_n90
mv /boot/script.bin /boot/sanei_n90-script.bin

%post szenio_1207c4
mv /boot/szenio_1207c4-script.bin /boot/script.bin

%preun szenio_1207c4
mv /boot/script.bin /boot/szenio_1207c4-script.bin

%post wobo-i5
mv /boot/wobo-i5-script.bin /boot/script.bin

%preun wobo-i5
mv /boot/script.bin /boot/wobo-i5-script.bin

%post xzpad700
mv /boot/xzpad700-script.bin /boot/script.bin

%preun xzpad700
mv /boot/script.bin /boot/xzpad700-script.bin

%post yarvik_tab260
mv /boot/yarvik_tab260-script.bin /boot/script.bin

%preun yarvik_tab260
mv /boot/script.bin /boot/yarvik_tab260-script.bin

%post jesurun-q5
mv /boot/jesurun-q5-script.bin /boot/script.bin

%preun jesurun-q5
mv /boot/script.bin /boot/jesurun-q5-script.bin


%files
%defattr(-,root,root,-)
%doc README
# >> files
# << files


%files a10_mid_1gb
%defattr(-,root,root,-)
/boot/a10_mid_1gb-script.bin
# >> files a10_mid_1gb
# << files a10_mid_1gb

%files ba10_tv_box
%defattr(-,root,root,-)
/boot/ba10_tv_box-script.bin
# >> files ba10_tv_box
# << files ba10_tv_box

%files coby_mid7042
%defattr(-,root,root,-)
/boot/coby_mid7042-script.bin
# >> files coby_mid7042
# << files coby_mid7042

%files coby_mid8042
%defattr(-,root,root,-)
/boot/coby_mid8042-script.bin
# >> files coby_mid8042
# << files coby_mid8042

%files coby_mid9742
%defattr(-,root,root,-)
/boot/coby_mid9742-script.bin
# >> files coby_mid9742
# << files coby_mid9742

%files cubieboard
%defattr(-,root,root,-)
/boot/cubieboard-script.bin
# >> files cubieboard
# << files cubieboard

%files cubieboard_512
%defattr(-,root,root,-)
/boot/cubieboard_512-script.bin
# >> files cubieboard_512
# << files cubieboard_512

%files dns_m82
%defattr(-,root,root,-)
/boot/dns_m82-script.bin
# >> files dns_m82
# << files dns_m82

%files gooseberry_a721
%defattr(-,root,root,-)
/boot/gooseberry_a721-script.bin
# >> files gooseberry_a721
# << files gooseberry_a721

%files h6
%defattr(-,root,root,-)
/boot/h6-script.bin
# >> files h6
# << files h6

%files hackberry
%defattr(-,root,root,-)
/boot/hackberry-script.bin
# >> files hackberry
# << files hackberry

%files hyundai_a7hd
%defattr(-,root,root,-)
/boot/hyundai_a7hd-script.bin
# >> files hyundai_a7hd
# << files hyundai_a7hd

%files inet97f-ii
%defattr(-,root,root,-)
/boot/inet97f-ii-script.bin
# >> files inet97f-ii
# << files inet97f-ii

%files mele_a1000
%defattr(-,root,root,-)
/boot/mele_a1000-script.bin
# >> files mele_a1000
# << files mele_a1000

%files mele_a1000g
%defattr(-,root,root,-)
/boot/mele_a1000g-script.bin
# >> files mele_a1000g
# << files mele_a1000g

%files mini-x-1gb
%defattr(-,root,root,-)
/boot/mini-x-1gb-script.bin
# >> files mini-x-1gb
# << files mini-x-1gb

%files mini-x
%defattr(-,root,root,-)
/boot/mini-x-script.bin
# >> files mini-x
# << files mini-x

%files mk802-1gb
%defattr(-,root,root,-)
/boot/mk802-1gb-script.bin
# >> files mk802-1gb
# << files mk802-1gb

%files mk802
%defattr(-,root,root,-)
/boot/mk802-script.bin
# >> files mk802
# << files mk802

%files mk802ii
%defattr(-,root,root,-)
/boot/mk802ii-script.bin
# >> files mk802ii
# << files mk802ii

%files pov_protab2_ips9
%defattr(-,root,root,-)
/boot/pov_protab2_ips9-script.bin
# >> files pov_protab2_ips9
# << files pov_protab2_ips9

%files pov_protab2_ips_3g
%defattr(-,root,root,-)
/boot/pov_protab2_ips_3g-script.bin
# >> files pov_protab2_ips_3g
# << files pov_protab2_ips_3g

%files uhost_u1a
%defattr(-,root,root,-)
/boot/uhost_u1a-script.bin
# >> files uhost_u1a
# << files uhost_u1a

%files zatab
%defattr(-,root,root,-)
/boot/zatab-script.bin
# >> files zatab
# << files zatab

%files mk802plus_a10s
%defattr(-,root,root,-)
/boot/mk802_a10s-script.bin
# >> files mk802plus_a10s
# << files mk802plus_a10s

%files r7
%defattr(-,root,root,-)
/boot/r7-tv-dongle-script.bin
# >> files r7
# << files r7

%files a13_mid
%defattr(-,root,root,-)
/boot/a13_mid-script.bin
# >> files a13_mid
# << files a13_mid

%files a13_olinuxino
%defattr(-,root,root,-)
/boot/a13-olinuxino-script.bin
# >> files a13_olinuxino
# << files a13_olinuxino

%files pcduino
%defattr(-,root,root,-)
/boot/pcduino-script.bin
# >> files pcduino
# << files pcduino

%files eoma68-a10
%defattr(-,root,root,-)
/boot/eoma68_a10-script.bin
# >> files eoma68-a10
# << files eoma68-a10

%files A31_EVB
%defattr(-,root,root,-)
/boot/A31_EVB-script.bin
# >> files A31_EVB
# << files A31_EVB

%files a10s-olinuxino-m-lcd10
%defattr(-,root,root,-)
/boot/a10s-olinuxino-m-lcd10-script.bin
# >> files a10s-olinuxino-m-lcd10
# << files a10s-olinuxino-m-lcd10

%files a10s-olinuxino-m-lcd7
%defattr(-,root,root,-)
/boot/a10s-olinuxino-m-lcd7-script.bin
# >> files a10s-olinuxino-m-lcd7
# << files a10s-olinuxino-m-lcd7

%files a10s-olinuxino-m
%defattr(-,root,root,-)
/boot/a10s-olinuxino-m-script.bin
# >> files a10s-olinuxino-m
# << files a10s-olinuxino-m

%files a13-olinuxino-lcd10
%defattr(-,root,root,-)
/boot/a13-olinuxino-lcd10-script.bin
# >> files a13-olinuxino-lcd10
# << files a13-olinuxino-lcd10

%files a13-olinuxino-lcd7
%defattr(-,root,root,-)
/boot/a13-olinuxino-lcd7-script.bin
# >> files a13-olinuxino-lcd7
# << files a13-olinuxino-lcd7

%files a13-olinuxinom-lcd10
%defattr(-,root,root,-)
/boot/a13-olinuxinom-lcd10-script.bin
# >> files a13-olinuxinom-lcd10
# << files a13-olinuxinom-lcd10

%files a13-olinuxinom-lcd7
%defattr(-,root,root,-)
/boot/a13-olinuxinom-lcd7-script.bin
# >> files a13-olinuxinom-lcd7
# << files a13-olinuxinom-lcd7

%files a13-olinuxinom
%defattr(-,root,root,-)
/boot/a13-olinuxinom-script.bin
# >> files a13-olinuxinom
# << files a13-olinuxinom

%files a20-olinuxino_micro-lcd10
%defattr(-,root,root,-)
/boot/a20-olinuxino_micro-lcd10-script.bin
# >> files a20-olinuxino_micro-lcd10
# << files a20-olinuxino_micro-lcd10

%files a20-olinuxino_micro-lcd7
%defattr(-,root,root,-)
/boot/a20-olinuxino_micro-lcd7-script.bin
# >> files a20-olinuxino_micro-lcd7
# << files a20-olinuxino_micro-lcd7

%files a20-olinuxino_micro
%defattr(-,root,root,-)
/boot/a20-olinuxino_micro-script.bin
# >> files a20-olinuxino_micro
# << files a20-olinuxino_micro

%files a70x
%defattr(-,root,root,-)
/boot/a70x-script.bin
# >> files a70x
# << files a70x

%files auxtek-t003
%defattr(-,root,root,-)
/boot/auxtek-t003-script.bin
# >> files auxtek-t003
# << files auxtek-t003

%files auxtek-t004
%defattr(-,root,root,-)
/boot/auxtek-t004-script.bin
# >> files auxtek-t004
# << files auxtek-t004

%files cubieboard2
%defattr(-,root,root,-)
/boot/cubieboard2-script.bin
# >> files cubieboard2
# << files cubieboard2

%files cubietruck
%defattr(-,root,root,-)
/boot/cubietruck-script.bin
# >> files cubietruck
# << files cubietruck

%files eu3000
%defattr(-,root,root,-)
/boot/eu3000-script.bin
# >> files eu3000
# << files eu3000

%files hd12-a20-v1
%defattr(-,root,root,-)
/boot/hd12-a20-v1-script.bin
# >> files hd12-a20-v1
# << files hd12-a20-v1

%files iteaduino_plus_a10
%defattr(-,root,root,-)
/boot/iteaduino_plus_a10-script.bin
# >> files iteaduino_plus_a10
# << files iteaduino_plus_a10


%files iteaduino_plus_a20
%defattr(-,root,root,-)
/boot/iteaduino_plus_a20-script.bin
# >> files iteaduino_plus_a20
# << files iteaduino_plus_a20

%files k1001l1c
%defattr(-,root,root,-)
/boot/k1001l1c-script.bin
# >> files k1001l1c
# << files k1001l1c

%files ltm7
%defattr(-,root,root,-)
/boot/ltm7-script.bin
# >> files ltm7
# << files ltm7

%files marsboard_a10
%defattr(-,root,root,-)
/boot/marsboard_a10-script.bin
# >> files marsboard_a10
# << files marsboard_a10

%files megafeis_a08
%defattr(-,root,root,-)
/boot/megafeis_a08-script.bin
# >> files megafeis_a08
# << files megafeis_a08

%files mele-a1000g-quad
%defattr(-,root,root,-)
/boot/mele-a1000g-quad-script.bin
# >> files mele-a1000g-quad
# << files mele-a1000g-quad

%files mele_a3700
%defattr(-,root,root,-)
/boot/mele_a3700-script.bin
# >> files mele_a3700
# << files mele_a3700

%files mini-x_a10s
%defattr(-,root,root,-)
/boot/mini-x_a10s-script.bin
# >> files mini-x_a10s
# << files mini-x_a10s

%files myaudio-708m
%defattr(-,root,root,-)
/boot/myaudio-708m-script.bin
# >> files myaudio-708m
# << files myaudio-708m

%files sanei_n90
%defattr(-,root,root,-)
/boot/sanei_n90-script.bin
# >> files sanei_n90
# << files sanei_n90

%files szenio_1207c4
%defattr(-,root,root,-)
/boot/szenio_1207c4-script.bin
# >> files szenio_1207c4
# << files szenio_1207c4

%files wobo-i5
%defattr(-,root,root,-)
/boot/wobo-i5-script.bin
# >> files wobo-i5
# << files wobo-i5

%files xzpad700
%defattr(-,root,root,-)
/boot/xzpad700-script.bin
# >> files xzpad700
# << files xzpad700

%files yarvik_tab260
%defattr(-,root,root,-)
/boot/yarvik_tab260-script.bin
# >> files yarvik_tab260
# << files yarvik_tab260

%files jesurun-q5
%defattr(-,root,root,-)
/boot/jesurun-q5-script.bin
# >> files jesurun-q5
# << files jesurun-q5
